name: The Development Den
markdown: redcarpet
pygments: true
markdown: kramdown

permalink: /:title

author: Martyn Hardy
email: martynthewolf@gmail.com
profession: Software Engineer
twitter: martynthewolf
repositories: martynthewolf
