name: The Development Den
markdown: redcarpet
pygments: true
markdown: kramdown

author: Martyn Hardy
email: martynthewolf@gmail.com
profession: Software Engineer
twitter: martynthewolf
github: martynthewolf
stackoverflow: martynthewolf
